### ISSUE TITLE
请教关于这个机械臂可以模拟任何机械臂吗？

### ISSUE THREAD

**Issue by wsgzxl** [JinghanSun/armSimulationByUnity3D#1]
我的方式有两个：       1.请问这样可以任何机械臂吗？都是采用三个空物体？
                                    2.别人给我一个角度我如何反转到，unity中的本地坐标呢？

**Comment by JinghanSun** [comment]
问题一：我这里机械臂的关节主要是解决旋转关节的实现，平移关节不予考虑。看你关节需要几个自由度了，如果单自由度的旋转关节，你在旋转轴那放置一个空物体进行辅助就可以了，我放置三个空物体是为了模拟三自由度的球关节。这个空物体个数根据你关机的复杂程度来确定。

问题二：你的意思是给出关节角怎么求末端位置相对于基座的相对位置么？  可以直接正向运动学求解呀。。。或者你懒得推位姿变换矩阵，那你就在场景中把关节角设置好，然后把末端物体赋为基座物体的子物体，然后调用末端物体的localposition就可以得到相对于基座的相对位置了。

**Comment by wsgzxl** [comment]
你好，可以加你QQ请教吗？我的QQ:1357098586!




------------------ 原始邮件 ------------------
发件人: "SunJinghan"<notifications@github.com>;
发送时间: 2018年11月8日(星期四) 下午4:47
收件人: "JinghanSun/armSimulationByUnity3D"<armSimulationByUnity3D@noreply.github.com>;
抄送: "老龙王"<1357098586@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [JinghanSun/armSimulationByUnity3D] 请教关于这个机械臂可以模拟任何机械臂吗？ (#1)




问题一：我这里机械臂的关节主要是解决旋转关节的实现，平移关节不予考虑。看你关节需要几个自由度了，如果单自由度的旋转关节，你在旋转轴那放置一个空物体进行辅助就可以了，我放置三个空物体是为了模拟三自由度的球关节。这个空物体个数根据你关机的复杂程度来确定。
 
问题二：你的意思是给出关节角怎么求末端位置相对于基座的相对位置么？  可以直接正向运动学求解呀。。。或者你懒得推位姿变换矩阵，那你就在场景中把关节角设置好，然后把末端物体赋为基座物体的子物体，然后调用末端物体的localposition就可以得到相对于基座的相对位置了。
